# Generated by Django 6.0.1 on 2026-01-14 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=20, unique=True, verbose_name='Kode Aset')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Serial')),
                ('brand', models.CharField(max_length=50, verbose_name='Merk')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('processor', models.CharField(max_length=100, verbose_name='Prosesor')),
                ('ram_gb', models.PositiveIntegerField(verbose_name='RAM (GB)')),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVME', 'NVMe SSD')], default='SSD', max_length=10, verbose_name='Tipe Storage')),
                ('storage_size_gb', models.PositiveIntegerField(verbose_name='Ukuran Storage (GB)')),
                ('gpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('assessed', 'Sudah Dinilai'), ('ready', 'Tersedia'), ('auction', 'Proses Lelang'), ('sold', 'Terjual'), ('used', 'Dipakai'), ('scrapped', 'Dibuang')], default='draft', max_length=20, verbose_name='Status')),
                ('physical_grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], max_length=1, null=True, verbose_name='Grade Fisik')),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Pembukaan')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Jual')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pembeli')),
                ('last_user', models.CharField(max_length=100, verbose_name='User Terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptop',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WSMCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kriteria')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Bobot')),
                ('attribute_type', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], default='benefit', max_length=10, verbose_name='Tipe Atribut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kriteria WSM',
                'verbose_name_plural': 'Kriteria WSM',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Buat'), ('update', 'Update'), ('delete', 'Hapus'), ('assess', 'Penilaian'), ('status_change', 'Ubah Status')], max_length=20, verbose_name='Aksi')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID Objek')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Deskripsi')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Perubahan')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Log Audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_condition', models.IntegerField(choices=[(5, 'Sangat Baik - Tidak ada cacat'), (4, 'Baik - Cacat minimal tidak terlihat'), (3, 'Cukup - Ada 1-2 titik whitespot'), (2, 'Kurang - Lecet kasar/deadpixel banyak'), (1, 'Rusak - Layar pecah/retak')], verbose_name='C1 - Kondisi Layar')),
                ('physical_condition', models.IntegerField(choices=[(5, 'Sangat Baik - Mulus seperti baru'), (4, 'Baik - Bekas pemakaian minimal'), (3, 'Cukup - Ada goresan halus'), (2, 'Kurang - Penyok/retak halus'), (1, 'Rusak - Rusak parah')], verbose_name='C2 - Kondisi Fisik')),
                ('battery_health', models.IntegerField(choices=[(5, 'Sangat Baik - >2 jam'), (4, 'Baik - 1-2 jam'), (3, 'Cukup - 30 menit - 1 jam'), (2, 'Kurang - <30 menit'), (1, 'Rusak - Perlu service/mati')], verbose_name='C3 - Kesehatan Baterai')),
                ('keyboard_status', models.IntegerField(choices=[(5, 'Normal - Semua tombol berfungsi'), (4, 'Baik - Bekas pemakaian minimal'), (3, 'Cukup - Ada tombol agak keras'), (2, 'Kurang - Ada tombol error'), (1, 'Rusak - Tidak berfungsi')], verbose_name='C4a - Keyboard')),
                ('touchpad_status', models.IntegerField(choices=[(5, 'Normal - Responsif sempurna'), (4, 'Baik - Bekas pemakaian minimal'), (3, 'Cukup - Agak kurang responsif'), (2, 'Kurang - Sering error'), (1, 'Rusak - Tidak berfungsi')], verbose_name='C4b - Touchpad')),
                ('specs_score', models.IntegerField(choices=[(5, 'Sangat Baik - High-end specs'), (4, 'Baik - Mid-high specs'), (3, 'Cukup - Mid specs'), (2, 'Kurang - Entry-level'), (1, 'Rusak - Outdated')], verbose_name='C5 - Spesifikasi Teknis')),
                ('power_status', models.BooleanField(default=True, verbose_name='Kondisi Daya Hidup')),
                ('connectivity_score', models.IntegerField(choices=[(5, 'Sangat Baik - Semua port berfungsi'), (4, 'Baik - 1 port minor tidak berfungsi'), (3, 'Cukup - 2 port tidak berfungsi'), (2, 'Kurang - Port utama bermasalah'), (1, 'Rusak - Mayoritas port rusak')], verbose_name='C6 - Konektivitas')),
                ('camera_ok', models.BooleanField(default=True, verbose_name='Kamera OK')),
                ('speaker_ok', models.BooleanField(default=True, verbose_name='Speaker OK')),
                ('usb_port_ok', models.BooleanField(default=True, verbose_name='Port USB OK')),
                ('hinge_broken', models.BooleanField(default=False, verbose_name='Engsel Rusak')),
                ('screw_missing', models.BooleanField(default=False, verbose_name='Baut Hilang')),
                ('dent_crack', models.BooleanField(default=False, verbose_name='Penyok/Retak')),
                ('wsm_score', models.FloatField(blank=True, null=True, verbose_name='Skor WSM')),
                ('final_grade', models.CharField(blank=True, max_length=1, null=True, verbose_name='Grade Akhir')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Catatan Kondisi')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Penilaian')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dinilai Oleh')),
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='inventory.laptop', verbose_name='Laptop')),
            ],
            options={
                'verbose_name': 'Penilaian',
                'verbose_name_plural': 'Penilaian',
            },
        ),
    ]
